openapi: 3.0.0
info:
  title: Basantara API
  description: This is an API documentation for the Basantara applications
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Alphabets:
      type: object
      properties:
        id:
          type: integer
          description: Object ID
        name:
          type: string
          description: Name of the alphabet
        descriptionID:
          type: string
          description: Description of the alphabet in Indonesian
        descriptionEN:
          type: string
          description: Description of the alphabet in English
        imgVector:
          type: string
          description: Image URL for the alphabet vector image
        imgReal:
          type: string
          description: Image URL for the alphabet real image
      example:
        id: 1
        name: a
        descriptionID: Regangkan jari telunjuk dan jempol kedua tangan dan tempelkan satu sama lain sehingga membentuk segitiga.
        descriptionEN: Extend the index finger and thumb of both hands and touch them together to form a triangle.
        imgVector: "https://storage.googleapis.com/basantara-assets/images-vector/a.png"
        imgReal: "https://storage.googleapis.com/basantara-assets/images/A.jpg"
    Users:
      type: object
      properties:
        username:
          type: string
          description: Name of the user
        email:
          type: string
          description: Email of the user
        password:
          type: string
          description: Password of the user
      example:
        username: tes
        email: tes@tes.com
        password: password
security:
  - bearerAuth: []
tags:
  - name: Alphabets
    description: The Alphabets API Endpoint
  - name: Users
    description: The Users API Endpoint
paths:
  /api/alphabets:
    get:
      summary: Get all alphabets sign language data
      tags: [Alphabets]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alphabets'
        404:
          description: Data not found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Service unavailable
  /api/alphabets/random:
    get:
      summary: Get random alphabet sign language data
      tags: [Alphabets]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alphabets'
              example:
                id: 1
                name: a
                descriptionID: Regangkan jari telunjuk dan jempol kedua tangan dan tempelkan satu sama lain sehingga membentuk segitiga.
                descriptionEN: Extend the index finger and thumb of both hands and touch them together to form a triangle.
                imgVector: "https://storage.googleapis.com/basantara-assets/images-vector/a.png"
                imgReal: "https://storage.googleapis.com/basantara-assets/images/A.jpg"
        404:
          description: Data not found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Service unavailable
  /api/users/register:
    post:
      summary: Register new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Users'
      responses:
        200:
          description: Register success
        400:
          description: Email Already Registered
        500:
          description: Internal server error
  /api/users/login:
    post:
      summary: Login
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string
                  description: Email of the user
                password:
                  type: string
                  description: Password of the user
              example:
                email: tes@tes.com
                password: password
      responses:
        200:
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
        400:
          description: Login failed
        500:
          description: Error message
